# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test
on: [push, pull_request, workflow_dispatch]

jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Mesa
      run: pip install mesa
    - name: Run model
      run: python run.py
      working-directory: boltzmann_wealth_model

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Mesa and pytest
      run: pip install mesa pytest
    - name: Test with Pytest
      run: pytest
      working-directory: boltzmann_wealth_model
